Move Time column to be first in list view
babybuddy/babybuddy pull request #250
Opened 2021-07-08 20:13 UTC by lutzky

Fixes #232

2021-07-09 14:39 UTC, cdubz requested changes
@lutzky let’s be consistent here and also make this change for the list view on other models — weight, temperature, notes, and timers.

2021-07-09 21:34 UTC, cdubz commented
@lutzky did something change here? I see a force push and review request but still just see the changes on the four main models.

2021-07-09 23:04 UTC, lutzky commented
Heh, first-time dad of a newborn messes up Git commands. Surprise 😆

2021-07-10 02:32 UTC, cdubz approved these changes

2021-07-10 02:32 UTC, merged