Fix ordering of start/stop items when start and stop times are the same
babybuddy/babybuddy pull request #372
Opened 2022-01-12 09:46 UTC by MrApplejuice

# Problem

It can be handy sometimes to retroactively add, for example, a "feeding" quickly from the menu without editing the start and end times explicitly. We make use of this feature a lot right when we are done with a feeding but forgot to start a timer for measuring the time it took to do the feeding. This makes it so that start and end times are stored as the same timepoint.

However, when viewing timeline items for these entries are ordered the "wrong way" (better said "illogical"), listing "start" after "end":

![grafik](https://user-images.githubusercontent.com/542105/149093925-ba5f140a-6cfa-45c8-a7ed-4b89e662a775.png)

# Solution

Use lexical ordering of `timeline_entry.type` in the template to force the order of entries at equal timepoints:

![grafik](https://user-images.githubusercontent.com/542105/149114173-655b60c4-19f0-4c76-b56c-d74022820a21.png)

2022-01-12 09:49 UTC, MrApplejuice commented on core/templates/timeline/_timeline.html
> +            {% for object in moment_objects.list|dictsort:"type" %}
This dictsort does the trick. However, the regroup is necessary to force sorting precedence on time, making this a bit more messy :-/

2022-01-13 00:37 UTC, cdubz requested changes

2022-01-17 15:00 UTC, MrApplejuice commented on core/templates/timeline/_timeline.html
> +            {% for object in moment_objects.list|dictsort:"type" %}
I picked (1)

2022-01-17 15:01 UTC, MrApplejuice commented
The change of L27 in timeline.py is a lot more clean. I was not sure if that is "acceptable" in the sense where the line with respect to rendering being agnostic to changes to the data. Anyway. This now is a two-liner and much more expressive with the explicit ordering as a dict.

I reverted the old change as well.

2022-01-17 15:26 UTC, cdubz commented
> I was not sure if that is "acceptable" in the sense where the line with respect to rendering being agnostic to changes to the data.

Yeah I tend to struggle with the separation of data and rendering and often get things mixed. So you’d be hard pressed to come up with something I wouldn’t find acceptable in that sense 😁

2022-01-17 15:26 UTC, cdubz approved these changes

2022-01-17 15:27 UTC, merged