feat: Weight percentiles in weight graph #512
babybuddy/babybuddy pull request #708
Opened 2023-09-20 15:58 UTC by barakplasma

fixes https://github.com/babybuddy/babybuddy/issues/512

2023-09-21 01:17 UTC, cdubz requested changes
When I open the PR in codspaces the `.devcontainer.json` file has modifications after everything boots up --

```diff
@cdubz ➜ /workspaces/babybuddy (weight-percentiles-in-weight-graph ✗) $ git diff .devcontainer.json 
diff --git a/.devcontainer.json b/.devcontainer.json
index 75877d8..7110e18 100644
--- a/.devcontainer.json
+++ b/.devcontainer.json
@@ -4,7 +4,8 @@
       "extensions": [
         "bbenoist.Nix",
         "ms-python.python",
-        "batisteo.vscode-django"
+        "batisteo.vscode-django",
+        "ms-python.black-formatter"
       ]
     }
   },
```

2023-09-21 01:17 UTC, cdubz commented on reports/graphs/weight_change.py
Can we limit the traces to only go as far as their is weight data? Having the full set in there causes some oddness in the graph:


https://github.com/babybuddy/babybuddy/assets/10456740/c0406348-328a-460f-a4d3-fe3e5fd8686f

2023-09-21 04:39 UTC, barakplasma commented on reports/graphs/weight_change.py
of course

2023-09-21 05:17 UTC, barakplasma commented on reports/graphs/weight_change.py
fixed in 1e8834c2078a4f5a79a8486213e3c098d0e279b8

2023-09-21 05:17 UTC, barakplasma commented
> When I open the PR in codspaces the `.devcontainer.json` file has modifications after everything boots up --
> 
> ```diff
> @cdubz ➜ /workspaces/babybuddy (weight-percentiles-in-weight-graph ✗) $ git diff .devcontainer.json 
> diff --git a/.devcontainer.json b/.devcontainer.json
> index 75877d8..7110e18 100644
> --- a/.devcontainer.json
> +++ b/.devcontainer.json
> @@ -4,7 +4,8 @@
>        "extensions": [
>          "bbenoist.Nix",
>          "ms-python.python",
> -        "batisteo.vscode-django"
> +        "batisteo.vscode-django",
> +        "ms-python.black-formatter"
>        ]
>      }
>    },
> ```

fixed as well

2023-09-27 13:24 UTC, cdubz approved these changes

2023-09-27 13:24 UTC, merged