feat: Height percentiles report (#719)
babybuddy/babybuddy pull request #741
Opened 2023-12-19 17:41 UTC by Lastpixl

Hi,

I really like the new WHO **w**eight percentile report... So, here is my contribution proposal: a similar **h**eight percentile report.

The implementation is really similar to that of the weight percentile report, it works in a dev environment. The instructions are great, writing this was pleasant! Kudos to the maintainers.
`makemessages` has generated fuzzy entries for french, I took the liberty of also fixing the few instances unrelated to this change for french.

Thanks for considering it for merging. Feel free to modify it in any way you see fit.

2023-12-22 14:33 UTC, cdubz requested changes
Thanks for contributing! Happy to hear it was easy to get going.

I have just one small CR for a variable naming.

Also could you modify: https://github.com/babybuddy/babybuddy/blob/1ef0bb9287adc4b47e74ec9cb2ac5164f142cc11/babybuddy/management/commands/fake.py#L89 to pick a starting fake height value that fits the model better? Right now when generating fake data and looking at these new reports we don't see any of the WHO lines because the test data is so much lower. Maybe set this to `self.height = round(uniform(45.0, 60.0), 2)`?

2023-12-22 14:33 UTC, cdubz commented on reports/graphs/height_change.py
> +    weighing_dates: list[datetime] = list(actual_heights.values_list("date", flat=True))
```suggestion
    measuring_dates: list[datetime] = list(actual_heights.values_list("date", flat=True))
```

2023-12-22 14:33 UTC, cdubz commented on reports/graphs/height_change.py
> +        x=weighing_dates,
```suggestion
        x=measuring_dates,
```

2023-12-23 15:18 UTC, Lastpixl commented on reports/graphs/height_change.py
> +    weighing_dates: list[datetime] = list(actual_heights.values_list("date", flat=True))
done

2023-12-23 15:19 UTC, Lastpixl commented on reports/graphs/height_change.py
> +        x=weighing_dates,
done

2023-12-23 15:19 UTC, Lastpixl commented on reports/graphs/height_change.py
> +        last_date_for_percentiles = max(weighing_dates) + timedelta(days=2)
done

2023-12-23 15:19 UTC, Lastpixl commented on reports/graphs/height_change.py
> +            max(weighing_dates) + timedelta(days=1),
done

2023-12-23 15:20 UTC, Lastpixl commented on reports/graphs/height_change.py
> +        # reduce percentile data xrange to end 1 day after last weigh in for formatting purposes
done

2023-12-23 15:23 UTC, Lastpixl commented
Thanks for the review, that was a lot of copypasta mistakes on my part... I have applied the requested changes, fixed an additional bug in my last commit.

2023-12-23 15:25 UTC, Lastpixl commented
Should I rebase this against master and update translation files to fix the conflict with `locale/zh/LC_MESSAGES/django.po`?

2023-12-23 16:00 UTC, cdubz commented
> Should I rebase this against master and update translation files to fix the conflict with `locale/zh/LC_MESSAGES/django.po`?

Oh shoot yeah I forgot this PR also had locale changes. Yes you’ll need to merge in or rebase on `master`.

2023-12-23 16:17 UTC, Lastpixl commented
Rebased on master, re-ran `gulp makemessages -a` then `gulp compilemessages` as part of the rebase of the first commit, the one that adds new strings.

2023-12-23 16:25 UTC, Lastpixl commented
One more rebase to fix formatting

2023-12-25 14:48 UTC, cdubz commented
Looks good. Thanks for contributing! :santa:

2023-12-25 14:48 UTC, merged