fix: Prevent 500 error when child object not passed
babybuddy/babybuddy pull request #886
Opened 2024-10-09 01:43 UTC by jcgoette

It's been awhile, so please double check me, but this should prevent 500/child.RelatedObjectDoesNotExist error when calling validate_unique_period without a child object provided.

2024-10-22 02:28 UTC, cdubz commented
@jcgoette 👋 Sorry for the delay getting to look at this. Do you repro steps I can test with?

2026-09-12 13:41 UTC, cdubz requested changes
Needs repo steps and/or test -- I am unclear what the issue is here.

2026-09-12 13:52 UTC, jcgoette commented
Nearly 2 years old at this point. Just close it out.

2026-09-12 13:52 UTC, closed without merging

2026-09-12 13:54 UTC, cdubz commented
💀